# services:
#   - type: web
#     name: flask-api
#     env: python
#     runtime: python-3.8
#     buildCommand: pip install -r requirements.txt
#     startCommand: python app.py
#     envVars:
#       - key: FLASK_ENV
#         value: production

services:
  - type: web
    name: flask-api
    env: python
    runtime: python-3.8
    buildCommand: |
      pip install -r requirements.txt
    startCommand: |
      gunicorn -w 4 -b 0.0.0.0:10000 app:app
    envVars:
      - key: FLASK_ENV
        value: production

